# .github/workflows/keep-warm.yml
name: Keep Render Warm
on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping render URLs
        run: |
          urls=(
          "https://youtube-clone-1-o85t.onrender.com"
            "https://youtube-operational-api-1.onrender.com"
          )
          for url in "${urls[@]}"; do
            code=$(curl -o /dev/null -s -w "%{http_code}" "$url")
            echo "$url -> Status $code"
          done
        shell: bash
        
